<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_ng Nhp_absolute right-5px top-8px h-6 w_d530b3</name>
   <tag></tag>
   <elementGuidId>9432296d-0071-4935-a437-7e6d05311a4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>a289752f-0d1b-4048-a53a-4adc42cb376f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>cebf9878-cb2c-4b18-82e4-8dd078c6e673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b755f443-ad6c-40ab-85ae-ed2fc8ff9cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>157212e1-70cb-4bc8-9864-e18a25e1257f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c5c6bd3c-bfe9-4af2-b70a-5017d16c1a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>80fd3d2b-b83c-4926-bb3c-c0f61703a117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute right-[5px] top-[8px] h-6 w-6 cursor-pointer opacity-60</value>
      <webElementGuid>792825be-0ee0-467d-91cd-08491484ed57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-orange&quot;]/div[@class=&quot;container py-[80px]&quot;]/div[@class=&quot;flex items-center justify-center lg:justify-end&quot;]/form[@class=&quot;min-h-[430px] w-[400px] rounded bg-[#fff] p-[30px] shadow-lg&quot;]/div[@class=&quot;mt-3&quot;]/div[@class=&quot;relative w-full&quot;]/svg[@class=&quot;absolute right-[5px] top-[8px] h-6 w-6 cursor-pointer opacity-60&quot;]</value>
      <webElementGuid>939ef880-89b6-4a81-8307-7e84883409c2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
