<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_confirm_registration</name>
   <tag></tag>
   <elementGuidId>32b4e118-6b94-419e-b710-799b63f61180</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d35da34f-79e8-4ace-9617-632e45783446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-3 w-full bg-orange/90 px-4 py-2 text-[#fff] hover:bg-orange</value>
      <webElementGuid>f92d1dde-f8c3-4661-a0ae-ce252cbabc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7bf2b21f-a88c-42f3-8261-006359bfb1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng Ký</value>
      <webElementGuid>38fa041d-88b9-404e-b5fe-f0666b217738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-orange&quot;]/div[@class=&quot;container py-[80px]&quot;]/div[@class=&quot;flex items-center justify-center lg:justify-end&quot;]/form[@class=&quot;min-h-[462px] w-[400px] rounded bg-[#fff] p-[30px] shadow-lg&quot;]/button[@class=&quot;mt-3 w-full bg-orange/90 px-4 py-2 text-[#fff] hover:bg-orange&quot;]</value>
      <webElementGuid>40bfd086-bbc8-42d7-bd5d-e0eb35d38c8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>1737caea-67c6-4eec-92a1-7f0a55e520bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/button</value>
      <webElementGuid>efd15e76-3683-43aa-82f5-0bae69df82fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>abcadf8a-fadc-4706-bb03-b3cf3015228a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Đăng Ký' or . = 'Đăng Ký')]</value>
      <webElementGuid>e6d9c314-16d7-4197-b52c-6370fee7cf17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
