<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_confirm_password</name>
   <tag></tag>
   <elementGuidId>8625f720-51c1-4c0e-be9c-48b5a2b8516c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;confirm_password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='confirm_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69dd826d-568f-458d-97d7-d714d3541e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative w-full outline-none border px-4 py-2 border-[#00000024] rounded-sm</value>
      <webElementGuid>a5bdc14b-d35c-4d1a-8847-85cd0e2df8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7b079bf8-7bcc-49f1-b930-98614fd57c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm_password</value>
      <webElementGuid>38bfa9ff-12d7-48fc-a239-a098929aebed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Xác nhận lại mật khẩu</value>
      <webElementGuid>a952dfe9-edda-45d1-8ea0-50dd0c6f1f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-orange&quot;]/div[@class=&quot;container py-[80px]&quot;]/div[@class=&quot;flex items-center justify-center lg:justify-end&quot;]/form[@class=&quot;min-h-[462px] w-[400px] rounded bg-[#fff] p-[30px] shadow-lg&quot;]/div[@class=&quot;mt-3&quot;]/div[@class=&quot;relative w-full&quot;]/input[@class=&quot;relative w-full outline-none border px-4 py-2 border-[#00000024] rounded-sm&quot;]</value>
      <webElementGuid>3f79e95d-371f-4e60-80f4-7e8c5046c3c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='confirm_password']</value>
      <webElementGuid>f40561fc-0686-4841-9ea0-3decf01a133f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[4]/div/input</value>
      <webElementGuid>09a119c7-2e4b-40f7-91aa-87916c0e0392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>8ae20563-eea0-4cad-88fb-f5f5bfb81b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirm_password' and @placeholder = 'Xác nhận lại mật khẩu']</value>
      <webElementGuid>2b12ed61-16ee-4261-9772-094c4b250a97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
