<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>488d6e05-e864-4058-8bda-e072921bcf34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8aa14e38-fa27-4ce0-be40-fd374e0847e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative w-full outline-none border px-4 py-2 border-[#00000024] rounded-sm</value>
      <webElementGuid>84fd4563-6d9a-477b-884a-a1afb30a2693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b2951c51-39c7-47fb-be24-a0e231eb7cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6ee3dd01-d744-481c-b657-62b7f9611044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật khẩu</value>
      <webElementGuid>86ddae1d-a4b8-49de-95b5-725f5c4a45b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-orange&quot;]/div[@class=&quot;container py-[80px]&quot;]/div[@class=&quot;flex items-center justify-center lg:justify-end&quot;]/form[@class=&quot;min-h-[462px] w-[400px] rounded bg-[#fff] p-[30px] shadow-lg&quot;]/div[@class=&quot;mt-3&quot;]/div[@class=&quot;relative w-full&quot;]/input[@class=&quot;relative w-full outline-none border px-4 py-2 border-[#00000024] rounded-sm&quot;]</value>
      <webElementGuid>e108394e-1c31-4dc9-bc3c-85d2d799e565</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>cd0bd30c-30a5-42ee-b9cf-998050936f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[3]/div/input</value>
      <webElementGuid>fdb5859d-bce9-407a-87b1-948bd691ab16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>2fc1baad-7033-44d2-899b-cca77dc79229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @placeholder = 'Mật khẩu']</value>
      <webElementGuid>65773218-818b-43ac-9acd-48dea8de40de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
