<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IconCart</name>
   <tag></tag>
   <elementGuidId>38f0985c-175f-4203-b59c-48ce89eda587</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@title='Xem trang giỏ hàng']//*[name()='svg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>polyline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>polyline</value>
      <webElementGuid>c926685f-7ab7-49ff-b58e-34cad6f9b60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>54c2bee8-26b0-4d75-95f0-bc6d4e0dd134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>points</name>
      <type>Main</type>
      <value>2 1.7 5.5 1.7 9.6 18.3 21.2 18.3 24.6 6.1 7 6.1</value>
      <webElementGuid>49333817-9cfe-4993-9b42-7e9018a3e7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>d0e49d49-70b7-437b-b9d0-a3fdbcd1abc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>0a8c016c-d2ae-484b-a961-f502515250e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-miterlimit</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>b700aa8b-6f04-4ac6-bfe3-635cb3d5a4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2.5</value>
      <webElementGuid>aef1bbe4-51b6-4e00-b4c8-37f8ad22db43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/header[@class=&quot;sticky inset-0 z-10&quot;]/div[@class=&quot;w-full bg-orange&quot;]/div[@class=&quot;container flex h-[5.3125rem] items-center justify-between py-4&quot;]/div[@class=&quot;mx-0 flex items-center justify-center md:mx-10&quot;]/div[1]/a[@class=&quot;relative block px-2 py-4 md:px-6&quot;]/svg[@class=&quot;h-[26px] w-auto fill-white stroke-white&quot;]/polyline[1]</value>
      <webElementGuid>b6c93a4b-b913-4f7b-908f-fd88dc91f692</webElementGuid>
   </webElementProperties>
</WebElementEntity>
