<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ng Nhp_email</name>
   <tag></tag>
   <elementGuidId>1d3f463c-01bf-459b-b4c9-dd94dc9a6d09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15fee24e-2a68-4c8a-b47d-b1fcb98b7462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none border px-4 py-2 border-[#00000024] rounded-sm</value>
      <webElementGuid>ced03a36-a22f-4d03-a274-da34c5c2a662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7865ae4b-3fce-4fda-8151-fbf343c78e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>4ff7393e-9f24-4762-956d-ac16697a78a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>b4fd83a2-246c-4afd-bb58-f200cccb4576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-orange&quot;]/div[@class=&quot;container py-[80px]&quot;]/div[@class=&quot;flex items-center justify-center lg:justify-end&quot;]/form[@class=&quot;min-h-[430px] w-[400px] rounded bg-[#fff] p-[30px] shadow-lg&quot;]/div[@class=&quot;mt-8&quot;]/div[@class=&quot;relative w-full&quot;]/input[@class=&quot;w-full outline-none border px-4 py-2 border-[#00000024] rounded-sm&quot;]</value>
      <webElementGuid>c21baec7-daff-488b-81e9-d6df9ae7123e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>90591c4c-30ee-4323-948b-9e680efe84ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/input</value>
      <webElementGuid>e52b5aa0-83a2-49db-9cca-51a86e1f3205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>587b4f5f-031d-4773-86cf-08a393a2fbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email' and @placeholder = 'Email']</value>
      <webElementGuid>54d90ebf-e208-4c5f-8df5-fbf15d4324dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
