<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_name(search)</name>
   <tag></tag>
   <elementGuidId>2eb86793-1a44-49c6-b039-6055e24dd39b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d32e038-6cd7-43f5-a198-d3a049094a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm kiếm....</value>
      <webElementGuid>77dac75a-77f8-4600-8e78-527d8a8efd10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fec8355c-628c-446c-aea3-04f984d44d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 w-full px-4 py-1 outline-none</value>
      <webElementGuid>8b224893-bfc3-437b-a788-80b7401aaf8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>567488c0-dcc6-4cfc-8d24-7b895a662310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/header[@class=&quot;sticky inset-0 z-10&quot;]/div[@class=&quot;w-full bg-orange&quot;]/div[@class=&quot;container flex h-[5.3125rem] items-center justify-between py-4&quot;]/form[@class=&quot;flex w-full items-center justify-between rounded-sm bg-white p-[3px] shadow&quot;]/input[@class=&quot;mr-2 w-full px-4 py-1 outline-none&quot;]</value>
      <webElementGuid>4328bcd1-4980-4748-9467-79ed553ed39b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='name']</value>
      <webElementGuid>943a6ef1-b05e-4ddb-bdd7-2803268e2675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/header/div[2]/div/form/input</value>
      <webElementGuid>9e52bf4a-d60a-47c0-8b64-266949f74fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>50b5a654-334b-4b6d-9044-38c30acdb67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tìm kiếm....' and @type = 'text' and @name = 'name']</value>
      <webElementGuid>ab19d5d5-8f0a-477d-9d22-ec7347a47753</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
