<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Shopee_cursor-pointer rounded-sm bg-_8d114d</name>
   <tag></tag>
   <elementGuidId>26413c10-f942-4847-b271-5a840b9613a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>be2cb889-f483-4ee7-a2ce-55c1afceb161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d620c739-c0f3-459a-a8ef-620ac1d30aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer rounded-sm bg-orange px-6 py-[10px] outline-none hover:bg-[#f05d40]</value>
      <webElementGuid>5d7aef5f-4e99-41e9-ba90-933d60520f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/header[@class=&quot;sticky inset-0 z-10&quot;]/div[@class=&quot;w-full bg-orange&quot;]/div[@class=&quot;container flex h-[5.3125rem] items-center justify-between py-4&quot;]/form[@class=&quot;flex w-full items-center justify-between rounded-sm bg-white p-[3px] shadow&quot;]/button[@class=&quot;cursor-pointer rounded-sm bg-orange px-6 py-[10px] outline-none hover:bg-[#f05d40]&quot;]</value>
      <webElementGuid>7edce673-6b09-4585-8c04-2e28b1152ebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>2238e236-1605-4f1a-a9cb-b90912ee608d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/header/div[2]/div/form/button</value>
      <webElementGuid>1b0c6984-f663-4ff1-a367-d2ed3b41bd2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>21af6878-042b-4ce4-ae0b-1bc98c72646c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit']</value>
      <webElementGuid>73e2f194-001a-4ca6-86b0-7acfc422a1d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
