<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shopee_name</name>
   <tag></tag>
   <elementGuidId>8c6485ef-98dc-48e3-8519-4149dd89e64e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da93e71a-f6f2-436b-b70b-55ece17bc3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm kiếm....</value>
      <webElementGuid>c3c8ca98-e3d4-4536-8ccf-8bf86715b121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76079149-c782-4295-99ff-751fbe9815f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 w-full px-4 py-1 outline-none</value>
      <webElementGuid>19fe55cc-9c97-431b-9f9e-4036ffde0200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>ce63739a-d3b7-4376-8667-0e3665296f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/header[@class=&quot;sticky inset-0 z-10&quot;]/div[@class=&quot;w-full bg-orange&quot;]/div[@class=&quot;container flex h-[5.3125rem] items-center justify-between py-4&quot;]/form[@class=&quot;flex w-full items-center justify-between rounded-sm bg-white p-[3px] shadow&quot;]/input[@class=&quot;mr-2 w-full px-4 py-1 outline-none&quot;]</value>
      <webElementGuid>dc7b2952-90dd-4d8e-b476-01d7ee65eabb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='name']</value>
      <webElementGuid>0059f185-05c0-41e8-a41e-4de21303c010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/header/div[2]/div/form/input</value>
      <webElementGuid>97ea6302-8482-4f4f-9e01-0fc223cb27b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1c74d534-a512-476e-9935-313d504d975a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tìm kiếm....' and @type = 'text' and @name = 'name']</value>
      <webElementGuid>798d0508-ae30-44cc-8b7a-089fe4d14fcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
