<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Gn nht</name>
   <tag></tag>
   <elementGuidId>40779286-a64c-4b23-ac08-b2f46f664121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ccd7237-6ff6-4fe0-8811-07576d789898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>min-w-[90px] rounded-sm px-[21px] py-[7px]  shadow-sm hover:opacity-80 bg-white text-black</value>
      <webElementGuid>35cf912b-f0db-4113-a914-9dd0228f0b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gần nhất</value>
      <webElementGuid>dcdf043b-a42d-42d8-ae15-052a63672a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;border-b-4 border-b-orange bg-[#f5f5f5] pb-[60px] pt-5&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;flex flex-col gap-5 md:flex-row&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;flex flex-wrap items-center gap-2 rounded-sm bg-[#ededed] px-5 py-[13px] lg:justify-between&quot;]/div[@class=&quot;flex flex-wrap items-center gap-[10px] text-sm&quot;]/button[@class=&quot;min-w-[90px] rounded-sm px-[21px] py-[7px]  shadow-sm hover:opacity-80 bg-white text-black&quot;]</value>
      <webElementGuid>aeca44f5-edba-4349-89cd-976d2aedd92f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/button[2]</value>
      <webElementGuid>a3a4ae20-0311-43a6-90c5-1c2094119af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>231608de-9aef-46d0-8e53-e4ab72ea25dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Gần nhất' or . = 'Gần nhất')]</value>
      <webElementGuid>d1307b19-1040-4b5e-9aab-b99c05c76543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
